TEXT_GAMEOVER = "GAME OVER";
TEXT_ARE_SURE = "ARE YOU SURE YOU WANT TO QUIT THE GAME?";
TEXT_SAVE_REMOVE = "THIS WILL REMOVE ALL YOUR ACHIEVEMENTS! DO YOU WANT TO PROCEED?"
TEXT_TOTAL_SCORE = "TOTAL SCORE";
TEXT_LAUNCH = "LAUNCH";
TEXT_HOLE = "HOLE";
TEXT_LOADING = "LOADING...";
TEXT_ALL_COMPLETE = "ALL LEVEL COMPLETED";
TEXT_SELECT_A_LEVEL = "SELECT A LEVEL";
TEXT_HELP1_PC = "CLICK THE BALL AND DRAG TO SET POWER AND DIRECTION";
TEXT_HELP1_MOBILE = "TOUCH THE BALL AND DRAG THE FINGER TO SET POWER AND DIRECTION";
TEXT_HELP2 = "CLICK AND DRAG TO HAVE A PAN VIEW";

TEXT_SCORE = "SCORE";
TEXT_COMPLETE = "COMPLETE";

TEXT_DEVELOPED = "DEVELOPED BY";
TEXT_LINK = "WWW.CODETHISLAB.COM";

TEXT_DOUBLE_BOGEY = "DOUBLE BOGEY";
TEXT_BOGEY = "BOGEY";
TEXT_PAR = "PAR";
TEXT_BIRDIE = "BIRDIE";
TEXT_EAGLE = "EAGLE";
TEXT_ALBATROSS = "ALBATROSS";
TEXT_CONDOR = "CONDOR";
TEXT_PHOENIX = "PHOENIX";
TEXT_HOLEINONE = "HOLE IN ONE";


TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better?";